# Generated by Django 3.1.14 on 2025-06-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('main_verticals', models.CharField(max_length=255)),
                ('monthly_revenue', models.CharField(max_length=100)),
                ('traffic_sources', models.TextField()),
            ],
        ),
    ]
