# Generated by Django 3.1.14 on 2025-06-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_affiliateprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateDailyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.affiliateprofile')),
            ],
        ),
    ]
