# Generated by Django 3.1.14 on 2025-06-14 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('country', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('sub1', models.CharField(blank=True, max_length=100, null=True)),
                ('sub2', models.CharField(blank=True, max_length=100, null=True)),
                ('sub3', models.CharField(blank=True, max_length=100, null=True)),
                ('sub4', models.CharField(blank=True, max_length=100, null=True)),
                ('sub5', models.CharField(blank=True, max_length=100, null=True)),
                ('ios_idfa', models.CharField(blank=True, max_length=100, null=True)),
                ('android_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cbid', models.CharField(blank=True, max_length=100, null=True)),
                ('uniq', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('iso', models.CharField(blank=True, max_length=2, null=True)),
                ('iso3', models.CharField(blank=True, max_length=3, null=True)),
                ('iso_numeric', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=5)),
                ('device', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('raw_clicks', models.IntegerField()),
                ('unique_clicks', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('charge', models.FloatField()),
                ('earning', models.FloatField()),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.affiliateprofile')),
            ],
            options={
                'verbose_name': 'Daily Stat',
                'ordering': ['-date'],
            },
        ),
    ]
