# Generated by Django 3.1.14 on 2025-06-14 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries_plus', '0001_initial'),
        ('offer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='affiliates',
            field=models.ManyToManyField(blank=True, related_name='affiliate_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(blank=True, to='offer.Category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='countries',
            field=models.ManyToManyField(blank=True, to='countries_plus.Country'),
        ),
        migrations.AddField(
            model_name='landing',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landings', to='offer.offer'),
        ),
        migrations.AddField(
            model_name='goal',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='offer.offer'),
        ),
        migrations.AlterUniqueTogether(
            name='offertrafficsource',
            unique_together={('offer', 'traffic_source')},
        ),
        migrations.AlterUniqueTogether(
            name='landing',
            unique_together={('offer', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('offer', 'name')},
        ),
    ]
