# Generated by Django 3.1.14 on 2025-06-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
