# Generated by Django 3.1.14 on 2025-06-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=500)),
                ('response_status', models.CharField(default='', max_length=10)),
                ('response_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Postback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('created', 'Created'), ('not_found', 'Not Found'), ('approved', 'Approved'), ('hold', 'Hold'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='created', max_length=20)),
                ('goal', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
