# Generated by Django 3.1.14 on 2025-06-14 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postback', '0001_initial'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postback',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postback',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postbacks', to='offer.offer'),
        ),
        migrations.AddField(
            model_name='log',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postback_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
