# Generated by Django 3.1.14 on 2025-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20250618_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
