# Generated by Django 3.1.14 on 2025-06-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
