# Generated by Django 3.1.14 on 2025-06-14 04:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub1', models.CharField(default='', max_length=500)),
                ('sub2', models.CharField(default='', max_length=500)),
                ('sub3', models.CharField(default='', max_length=500)),
                ('sub4', models.CharField(default='', max_length=500)),
                ('sub5', models.CharField(default='', max_length=500)),
                ('ip', models.GenericIPAddressField()),
                ('country', models.CharField(default='', max_length=2)),
                ('ua', models.CharField(default='', max_length=200)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('ip_local_time', models.DateTimeField(blank=True, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_date', models.DateTimeField(blank=True, null=True)),
                ('sub1', models.CharField(blank=True, default='', max_length=500)),
                ('sub2', models.CharField(blank=True, default='', max_length=500)),
                ('sub3', models.CharField(blank=True, default='', max_length=500)),
                ('sub4', models.CharField(blank=True, default='', max_length=500)),
                ('sub5', models.CharField(blank=True, default='', max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('ua', models.CharField(blank=True, default='', max_length=200)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('ip_local_time', models.DateTimeField(blank=True, null=True)),
                ('goal_value', models.CharField(default='', max_length=20)),
                ('sum', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('hold', 'Hold'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='rejected', max_length=10)),
                ('comment', models.CharField(blank=True, default='', max_length=128)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
