# Generated by Django 3.1.14 on 2025-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20250613_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='click',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='click',
            name='sub1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='click',
            name='sub2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='click',
            name='sub3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='click',
            name='sub4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='click',
            name='sub5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='click',
            name='ua',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='goal_value',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
