# Generated by Django 3.1.14 on 2025-06-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20250615_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
