# Generated by Django 3.1.14 on 2025-06-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_click_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
