# Generated by Django 3.1.14 on 2025-06-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_conversion_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
