# Generated by Django 3.1.14 on 2025-06-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_click_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='isp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversion',
            name='isp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
